name: bipolar_factory_assignment
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  camera: ^0.5.8+5
  path_provider: ^1.6.14
  video_player: ^0.10.12+2
  thumbnails:
    git:
      url: https://github.com/divyanshub024/Flutter_Thumbnails.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
